[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "monster-slicing"
version = "0.1.0"
description = "A game where you slice monsters"
dependencies = [
    "pygame>=2.6.1",
]

[tool.setuptools]
packages = ["monster_slicing"]
